from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Optional


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
        shell=False,
        check=False,
    )


def _extract_repo_url(*texts: str) -> Optional[str]:
    for text in texts:
        if not text:
            continue
        match = re.search(r"https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", text)
        if match:
            return match.group(0)
    return None


def create_github_repo(project_dir: Path) -> Optional[str]:
    project_dir = project_dir.expanduser().resolve()
    if not project_dir.exists() or not project_dir.is_dir():
        return None

    git_dir = project_dir / ".git"
    if not git_dir.exists():
        init_result = _run(["git", "init"], cwd=project_dir)
        if init_result.returncode != 0:
            return None

    add_result = _run(["git", "add", "."], cwd=project_dir)
    if add_result.returncode != 0:
        return None

    commit_result = _run(
        ["git", "commit", "-m", "Initial commit (generated by ArchMind)"],
        cwd=project_dir,
    )
    if commit_result.returncode != 0:
        combined = f"{commit_result.stdout}\n{commit_result.stderr}".lower()
        if "nothing to commit" not in combined and "working tree clean" not in combined:
            return None

    repo_name = project_dir.name
    create_result = _run(
        [
            "gh",
            "repo",
            "create",
            repo_name,
            "--private",
            "--source",
            str(project_dir),
            "--push",
        ],
        cwd=project_dir,
    )
    if create_result.returncode != 0:
        return None

    repo_url = _extract_repo_url(create_result.stdout, create_result.stderr)
    if repo_url:
        return repo_url

    view_result = _run(["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"], cwd=project_dir)
    if view_result.returncode != 0:
        return None
    value = (view_result.stdout or "").strip()
    return value or None
