from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Optional


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
        shell=False,
        check=False,
    )


def _extract_repo_url(*texts: str) -> Optional[str]:
    for text in texts:
        if not text:
            continue
        match = re.search(r"https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", text)
        if match:
            return match.group(0)
    return None


def _split_display_name(project_dir: Path) -> tuple[str, str]:
    display_name = project_dir.name
    matched = re.match(r"^(\d{8}_\d{6})(?:[_-]+(.*))?$", display_name)
    if not matched:
        return "", display_name
    project_id = str(matched.group(1) or "").strip()
    tail = str(matched.group(2) or "").strip()
    return project_id, tail


def _sanitize_english_slug(value: str, max_len: int = 24) -> str:
    text = str(value or "").strip().lower()
    text = text.replace("_", " ").replace("-", " ")
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", "-", text).strip("-")
    if not text:
        return "project"
    return text[:max_len].strip("-") or "project"


def _build_repo_slug(project_dir: Path) -> str:
    project_id, raw_tail = _split_display_name(project_dir)
    short_english_slug = _sanitize_english_slug(raw_tail or project_dir.name)
    if project_id:
        return f"{project_id}_{short_english_slug}"
    return short_english_slug


def create_github_repo(project_dir: Path) -> Optional[str]:
    project_dir = project_dir.expanduser().resolve()
    if not project_dir.exists() or not project_dir.is_dir():
        return None

    git_dir = project_dir / ".git"
    if not git_dir.exists():
        init_result = _run(["git", "init"], cwd=project_dir)
        if init_result.returncode != 0:
            return None

    add_result = _run(["git", "add", "."], cwd=project_dir)
    if add_result.returncode != 0:
        return None

    commit_result = _run(
        ["git", "commit", "-m", "Initial commit (generated by ArchMind)"],
        cwd=project_dir,
    )
    if commit_result.returncode != 0:
        combined = f"{commit_result.stdout}\n{commit_result.stderr}".lower()
        if "nothing to commit" not in combined and "working tree clean" not in combined:
            return None

    repo_slug = _build_repo_slug(project_dir)
    create_result = _run(
        [
            "gh",
            "repo",
            "create",
            repo_slug,
            "--private",
            "--source",
            str(project_dir),
            "--push",
        ],
        cwd=project_dir,
    )
    if create_result.returncode != 0:
        return None

    repo_url = _extract_repo_url(create_result.stdout, create_result.stderr)
    if repo_url:
        return repo_url

    view_result = _run(["gh", "repo", "view", repo_slug, "--json", "url", "-q", ".url"], cwd=project_dir)
    if view_result.returncode != 0:
        return None
    value = (view_result.stdout or "").strip()
    return value or None
