from __future__ import annotations

from typing import Dict

from archmind.templates.fullstack_ddd import enforce_fullstack_ddd


def enforce_data_tool(_: Dict[str, str], project_name: str) -> Dict[str, str]:
    files = enforce_fullstack_ddd({}, project_name)

    files["frontend/app/page.tsx"] = """const rows = [
  { id: "R-100", metric: "Revenue", value: "12000" },
  { id: "R-101", metric: "Orders", value: "348" },
  { id: "R-102", metric: "Inventory Alerts", value: "6" },
];

export default function DataToolHomePage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-slate-100">
      <section className="mx-auto max-w-5xl rounded-2xl border border-slate-800 bg-slate-900 p-6">
        <h1 className="text-2xl font-semibold">Data Tool Dashboard</h1>
        <p className="mt-2 text-sm text-slate-300">
          Starter table for data viewing and lightweight management workflows.
        </p>
        <div className="mt-6 overflow-x-auto">
          <table className="min-w-full border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-slate-700 text-slate-300">
                <th className="py-2 pr-4">Row</th>
                <th className="py-2 pr-4">Metric</th>
                <th className="py-2 pr-4">Value</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id} className="border-b border-slate-800">
                  <td className="py-2 pr-4">{row.id}</td>
                  <td className="py-2 pr-4">{row.metric}</td>
                  <td className="py-2 pr-4">{row.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
"""

    files["README.md"] = f"""# {project_name}

Generated by ArchMind `data-tool` template.

## What This Template Is For
- Internal data viewer / analytics / admin-style tools
- Dashboard + table oriented user flows

## Backend setup
```bash
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
```

## Backend run
```bash
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port ${{PORT:-8000}}
```

## Frontend setup
```bash
cd frontend
npm install
cp -n .env.example .env
```

## Frontend run
```bash
npm run dev
```

## Tests
```bash
python -m pytest -q
```
"""
    return files
