# src/archmind/templates/fastapi_ddd.py
from __future__ import annotations

from typing import Dict


def enforce_fastapi_ddd(_: Dict[str, str], project_name: str) -> Dict[str, str]:
    """
    Deterministic FastAPI DDD-ish template.
    Model output is ignored completely.
    """
    files: Dict[str, str] = {}

    # =========================
    # tests: make imports stable anywhere
    # =========================
    files["tests/conftest.py"] = """import sys
from pathlib import Path

# Ensure project root is importable so `import app` works no matter where pytest is run from.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
"""

    files["tests/test_health.py"] = """from fastapi.testclient import TestClient
from app.main import app

def test_health():
    client = TestClient(app)
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"
"""

    # =========================
    # README
    # =========================
    files["README.md"] = (
    f"# {project_name}\n\n"
    "FastAPI DDD-style project generated by ArchMind.\n\n"
    "## Setup\n"
    "```bash\n"
    "python3 -m venv .venv\n"
    "source .venv/bin/activate\n"
    "python -m pip install -r requirements.txt\n"
    "```\n\n"
    "## Test\n"
    "```bash\n"
    "pytest -q\n"
    "```\n\n"
    "## Run\n"
    "```bash\n"
    "uvicorn app.main:app --reload --port 8000\n"
    "```\n\n"
    "## Health Check\n"
    "```bash\n"
    "curl -s http://localhost:8000/health\n"
    "```\n"
)