from __future__ import annotations

from typing import Dict


def enforce_fullstack_ddd(_: Dict[str, str], project_name: str) -> Dict[str, str]:
    """
    Deterministic Fullstack DDD template (domain-neutral baseline).

    This template intentionally ships only generic shell structure.
    Domain entities/APIs/pages are added later from project spec via generator scaffolds.
    """
    files: Dict[str, str] = {}

    files["backend/requirements.txt"] = (
        "fastapi==0.115.0\n"
        "uvicorn[standard]==0.30.6\n"
        "pydantic==2.8.2\n"
        "pydantic-settings==2.4.0\n"
        "pytest==9.0.2\n"
        "httpx==0.27.0\n"
    )

    files["backend/pytest.ini"] = (
        "[pytest]\n"
        "testpaths = tests\n"
        "addopts = -q\n"
    )

    files["backend/.env.example"] = (
        f"APP_NAME={project_name}\n"
        "APP_PORT=8000\n"
        "BACKEND_BASE_URL=http://127.0.0.1:8000\n"
        "CORS_ALLOW_ORIGINS=http://localhost:3000,http://127.0.0.1:3000\n"
    )

    for package in [
        "backend/app/__init__.py",
        "backend/app/api/__init__.py",
        "backend/app/api/routers/__init__.py",
        "backend/app/core/__init__.py",
        "backend/tests/__init__.py",
    ]:
        files[package] = ""

    files["backend/app/core/settings.py"] = f"""from __future__ import annotations

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=(".env", "backend/.env"), extra="ignore")

    app_name: str = "{project_name}"
    app_port: int = 8000
    backend_base_url: str = "http://127.0.0.1:8000"
    cors_allow_origins: str = "http://localhost:3000,http://127.0.0.1:3000"


settings = Settings()
"""

    files["backend/app/api/router.py"] = """from fastapi import APIRouter

from app.api.routers.health import router as health_router

api_router = APIRouter()
api_router.include_router(health_router)
"""

    files["backend/app/api/routers/health.py"] = """from fastapi import APIRouter

router = APIRouter(tags=["health"])


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}
"""

    files["backend/app/main.py"] = """from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.router import api_router
from app.core.settings import settings

app = FastAPI(title=settings.app_name)

allow_origins = [x.strip() for x in settings.cors_allow_origins.split(",") if x.strip()]
if not allow_origins:
    allow_origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router)
"""

    files["backend/tests/test_health.py"] = """from fastapi.testclient import TestClient

from app.main import app


def test_health() -> None:
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
"""

    files["frontend/package.json"] = """{
  "name": "archmind-fullstack-frontend",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "sh -c 'next start -p ${PORT:-3000}'",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "20.14.10",
    "@types/react": "18.3.3",
    "@types/react-dom": "18.3.0",
    "autoprefixer": "10.4.19",
    "eslint": "8.57.0",
    "eslint-config-next": "14.2.5",
    "postcss": "8.4.39",
    "tailwindcss": "3.4.7",
    "typescript": "5.5.4"
  }
}
"""

    files["frontend/.env.example"] = (
        "NEXT_PUBLIC_API_BASE_URL=\n"
        "NEXT_PUBLIC_RUNTIME_BACKEND_URL=\n"
        "NEXT_PUBLIC_BACKEND_PORT=\n"
        "NEXT_PUBLIC_FRONTEND_PORT=\n"
    )

    files["frontend/next.config.js"] = """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
"""

    files["frontend/tsconfig.json"] = """{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

    files["frontend/next-env.d.ts"] = """/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js
"""

    files["frontend/.eslintrc.json"] = '{\n  "extends": ["next/core-web-vitals"]\n}\n'

    files["frontend/postcss.config.js"] = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""

    files["frontend/tailwind.config.ts"] = """import type { Config } from \"tailwindcss\";

const config: Config = {
  content: [
    \"./app/**/*.{js,ts,jsx,tsx,mdx}\",
    \"./components/**/*.{js,ts,jsx,tsx,mdx}\",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
"""

    files["frontend/app/globals.css"] = """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

body {
  margin: 0;
  background: #020617;
  color: #e2e8f0;
}
"""

    files["frontend/app/layout.tsx"] = f"""import \"./globals.css\";

export const metadata = {{
  title: \"{project_name}\",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang=\"en\">
      <body>
        <main className=\"mx-auto min-h-screen max-w-4xl p-6\">{{children}}</main>
      </body>
    </html>
  );
}}
"""

    files["frontend/app/page.tsx"] = """export default function HomePage() {
  return (
    <section className=\"space-y-3 rounded-xl border border-slate-800 bg-slate-900/60 p-6\">
      <h1 className=\"text-2xl font-semibold\">ArchMind Fullstack Workspace</h1>
      <p className=\"text-sm text-slate-300\">
        This scaffold is domain-neutral. Entities, APIs, and pages are generated from project spec.
      </p>
    </section>
  );
}
"""

    files["README.md"] = f"""# {project_name}

Generated by ArchMind `fullstack-ddd` template.

This baseline is intentionally domain-neutral.
Use project spec driven scaffolding (`entities`, `api_endpoints`, `frontend_pages`) to materialize domain features.

## Backend setup
```bash
cd backend
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
```

## Backend run
```bash
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port ${{PORT:-8000}}
```

## Frontend setup
```bash
cd frontend
npm install
cp -n .env.example .env
```

## Frontend run
```bash
npm run dev
```
"""

    files["scripts/dev.sh"] = """#!/usr/bin/env bash
set -euo pipefail

(
  cd backend
  python -m uvicorn app.main:app --reload --host 127.0.0.1 --port "${BACKEND_PORT:-8000}"
) &
BACK_PID=$!

(
  cd frontend
  npm run dev -- --hostname 127.0.0.1 --port "${FRONTEND_PORT:-3000}"
) &
FRONT_PID=$!

trap 'kill "$BACK_PID" "$FRONT_PID"' EXIT
wait
"""

    return files
