from __future__ import annotations

from typing import Dict

from archmind.templates.fullstack_ddd import enforce_fullstack_ddd


def enforce_internal_tool(_: Dict[str, str], project_name: str) -> Dict[str, str]:
    files = enforce_fullstack_ddd({}, project_name)

    files["frontend/app/page.tsx"] = """export default function InternalHomePage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-slate-100">
      <section className="mx-auto max-w-5xl rounded-2xl border border-slate-800 bg-slate-900 p-6">
        <h1 className="text-2xl font-semibold">Internal Operations Dashboard</h1>
        <p className="mt-2 text-sm text-slate-300">
          Internal-tool scaffold generated by ArchMind. Focus on admin workflows and operational visibility.
        </p>
      </section>
    </main>
  );
}
"""

    files["README.md"] = f"""# {project_name}

Generated by ArchMind `internal-tool` template.

## What This Template Is For
- Internal/admin workflows
- Dashboard-centric UI and operational views
- Backend + frontend scaffold with runtime-neutral commands

## Backend setup
```bash
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
```

## Backend run
```bash
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port ${{PORT:-8000}}
```

## Frontend setup
```bash
cd frontend
npm install
cp -n .env.example .env
```

## Frontend run
```bash
npm run dev
```

## Tests
```bash
python -m pytest -q
```
"""
    return files
