from __future__ import annotations


def enforce_nextjs_runtime(_files: dict[str, str], project_name: str) -> dict[str, str]:
    safe_name = (project_name or "archmind-nextjs-app").strip().lower().replace(" ", "-")
    if not safe_name:
        safe_name = "archmind-nextjs-app"

    files: dict[str, str] = {}
    files["package.json"] = (
        "{\n"
        f'  "name": "{safe_name}",\n'
        '  "private": true,\n'
        '  "version": "0.1.0",\n'
        '  "scripts": {\n'
        '    "dev": "next dev -p 5173",\n'
        '    "build": "next build",\n'
        '    "start": "sh -c \'next start -p ${PORT:-3000}\'",\n'
        '    "lint": "next lint"\n'
        "  },\n"
        '  "dependencies": {\n'
        '    "next": "14.2.5",\n'
        '    "react": "18.3.1",\n'
        '    "react-dom": "18.3.1"\n'
        "  },\n"
        '  "devDependencies": {\n'
        '    "@types/node": "20.14.12",\n'
        '    "@types/react": "18.3.3",\n'
        '    "@types/react-dom": "18.3.0",\n'
        '    "eslint": "8.57.0",\n'
        '    "eslint-config-next": "14.2.5",\n'
        '    "typescript": "5.5.4"\n'
        "  }\n"
        "}\n"
    )
    files["next.config.mjs"] = "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\n\nexport default nextConfig\n"
    files["tsconfig.json"] = (
        "{\n"
        '  "compilerOptions": {\n'
        '    "target": "ES2020",\n'
        '    "lib": ["dom", "dom.iterable", "esnext"],\n'
        '    "allowJs": false,\n'
        '    "skipLibCheck": true,\n'
        '    "strict": true,\n'
        '    "noEmit": true,\n'
        '    "esModuleInterop": true,\n'
        '    "module": "esnext",\n'
        '    "moduleResolution": "bundler",\n'
        '    "resolveJsonModule": true,\n'
        '    "isolatedModules": true,\n'
        '    "jsx": "preserve",\n'
        '    "incremental": true,\n'
        '    "plugins": [{"name": "next"}]\n'
        "  },\n"
        '  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],\n'
        '  "exclude": ["node_modules"]\n'
        "}\n"
    )
    files["next-env.d.ts"] = "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// Do not edit this file.\n"
    files["app/layout.tsx"] = (
        "import type { Metadata } from \"next\";\n"
        "import \"./globals.css\";\n\n"
        "export const metadata: Metadata = {\n"
        f"  title: \"{project_name}\",\n"
        "  description: \"Generated by ArchMind nextjs template\",\n"
        "};\n\n"
        "export default function RootLayout({ children }: { children: React.ReactNode }) {\n"
        "  return (\n"
        "    <html lang=\"en\">\n"
        "      <body>{children}</body>\n"
        "    </html>\n"
        "  );\n"
        "}\n"
    )
    files["app/page.tsx"] = (
        "export default function HomePage() {\n"
        "  return (\n"
        "    <main style={{ fontFamily: \"system-ui\", padding: 24 }}>\n"
        "      <h1>ArchMind Next.js Starter</h1>\n"
        "      <p>Frontend scaffold generated from idea routing.</p>\n"
        "    </main>\n"
        "  );\n"
        "}\n"
    )
    files["app/globals.css"] = (
        ":root {\n"
        "  color-scheme: light;\n"
        "}\n\n"
        "html, body {\n"
        "  margin: 0;\n"
        "  padding: 0;\n"
        "}\n"
    )
    files[".eslintrc.json"] = '{\n  "extends": ["next/core-web-vitals"]\n}\n'
    files[".gitignore"] = (
        "node_modules/\n"
        ".next/\n"
        "out/\n"
        ".env*\n"
        "npm-debug.log*\n"
        "yarn-debug.log*\n"
        "yarn-error.log*\n"
    )
    files["README.md"] = (
        f"# {project_name}\n\n"
        "Generated by ArchMind `nextjs` template.\n\n"
        "## Commands\n\n"
        "- `npm install`\n"
        "- `npm run dev`\n"
        "- `npm run lint`\n"
        "- `npm run build`\n"
    )
    return files
