from __future__ import annotations

from typing import Dict

from archmind.templates.fastapi_ddd import enforce_fastapi_ddd


def enforce_worker_api(_: Dict[str, str], project_name: str) -> Dict[str, str]:
    files = enforce_fastapi_ddd({}, project_name)

    files["app/workers/__init__.py"] = ""
    files["app/workers/tasks.py"] = """from __future__ import annotations


def run_background_batch() -> dict[str, str]:
    # Placeholder for queue/job integration in later sprints.
    return {"status": "queued", "detail": "worker placeholder task accepted"}
"""

    files["app/api/routers/worker.py"] = """from __future__ import annotations

from fastapi import APIRouter

from app.workers.tasks import run_background_batch

router = APIRouter(prefix="/worker", tags=["worker"])


@router.post("/run")
def run_worker_job() -> dict[str, str]:
    return run_background_batch()
"""

    api_router_py = files.get("app/api/router.py", "")
    if "from app.api.routers.worker import router as worker_router" not in api_router_py:
        api_router_py = api_router_py.replace(
            "from app.api.routers.defects import router as defects_router\n",
            "from app.api.routers.defects import router as defects_router\n"
            "from app.api.routers.worker import router as worker_router\n",
        )
        api_router_py = api_router_py.replace(
            "api_router.include_router(defects_router)\n",
            "api_router.include_router(defects_router)\napi_router.include_router(worker_router)\n",
        )
    files["app/api/router.py"] = api_router_py

    files["README.md"] = f"""# {project_name}

Generated by ArchMind `worker-api` template.

## What This Template Is For
- API-first backend projects with background/worker jobs
- Queue/batch-ready structure using placeholders

## Backend setup
```bash
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
```

## Backend run
```bash
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port ${{PORT:-8000}}
```

## Worker endpoint
- `POST /worker/run` : triggers a placeholder background batch task

## Tests
```bash
python -m pytest -q
```
"""
    return files
